### ISSUE TITLE
initials and bg-color not work into ng-repeat with $scope values

### ISSUE THREAD

**Issue by nokiajavi** [ajsoriar/angular-avatar#15]
initials and bg-color not work into ng-repeat with $scope values

Model Client (Array Client) $scope.clients:
[{id: 1,
color: '#134245',
 initials: 'AA'
},{id: 2,
color: '#765434',
initials: 'AB'},...]
Example 1:
```
<ion-item collection-repeat="client in clients track by client.id" >
   <ng-avatar bg-color="{{client.color}}" initials="{{cliente.initials}}" round-shape="true" width="32"></ng-avatar>
</ion-item>

```
Example 2 (Without moustaches):
```
<ion-item collection-repeat="client in clients track by client.id" >
   <ng-avatar bg-color="client.color" initials="cliente.initials" round-shape="true" width="32"></ng-avatar>
</ion-item>

```

**Comment by jpmnteiro** [comment]
@nokiajavi just had a similar problem, you need to add `bind="true"` to your example 1.
