### ISSUE TITLE
Avatar not loading when initials came from controller

### ISSUE THREAD

**Issue by davidbranco** [ajsoriar/angular-avatar#19]
I'm trying to use ng-avatar and bring initials from controller.
That's my code:
`<ng-avatar width="50" initials="{{process.CUSTOMER.NAME}}" auto-color="true" text-shadow="true" font-weight="700" font-scale="80"
                                                round-shape="true"></ng-avatar>`

The `{{process.CUSTOMER.NAME}}` is correct and in a simple label we can see the letters, but in ng-avatar only show a gray rounded image.

But if set initials manually, everthing works.

Tks!

**Comment by ajsoriar** [comment]
Hello. You need to add bind="true", this way ng-avatar will listen for changes in the controller.

**Comment by ajsoriar** [comment]
check out this example: https://github.com/ajsoriar/angular-avatar/blob/master/demo/demo-3.html

**Comment by davidbranco** [comment]
Many thanks, @ajsoriar.
Your answer worked.
