### ISSUE TITLE
auto-color does not give unique color if two individuals have name starting from same alphabet with max-length as 1

### ISSUE THREAD

**Issue by frankyvij** [ajsoriar/angular-avatar#20]
If two individuals have different names but the names are starting with the same alphabet, then ng-avatar will not give unique colors to both individuals.

Refer to the example here:
https://plnkr.co/edit/aVGFUZUUf6gKSO1E3yFf?p=preview

**Comment by ajsoriar** [comment]
Please use **use-full-string-for-colors="true"**

When using **auto-color** and **string**, the option **use-full-string-for-colors** will determine the color based on all of the characters in the string, not just the initials
