### ISSUE TITLE
How to use colors-palette attribute?

### ISSUE THREAD

**Issue by piyush-ally** [ajsoriar/angular-avatar#26]
Can someone please add an example to use colors-palette attribute to READ.me?

**Comment by ajsoriar** [comment]
You will find two examples here: [https://github.com/ajsoriar/angular-avatar/blob/master/demo/demo-4.html](https://github.com/ajsoriar/angular-avatar/blob/master/demo/demo-4.html)

**(1) Add colors to an array:** 

`$scope.new_palette = ["#d3e22b","#bbd534","#a6ca3a","#8fbe3d","#79b340","#63aa42","#48a044","#249744"]; `

**(2) Use the component:**

`<ng-avatar initials="AS" width="30" auto-color="true" colors-palette="new_palette" class="avatar" font-weight="800" font-scale="125" corner-radius="3" text-shadow="true" ></ng-avatar>`

**Comment by piyush-ally** [comment]
@ajsoriar Thank you very much
